name: Lint and Test
on: [push]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m install --upgrade pip pdm
          pdm install
      - name: Lint
        run: pdm run lint
      - name: Run tests
        run: pdm run test
